# Generated by Django 2.1.5 on 2022-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220118_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='herbal4.jpeg', upload_to='projectpics'),
        ),
    ]
