# Generated by Django 2.1.5 on 2022-01-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
