# Generated by Django 2.1.5 on 2022-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220122_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='projectpics'),
        ),
    ]
